[build]
# target = "x86_64-unknown-linux-musl"

# or
# target = "x86_64-unknown-linux-gnu"
# with flag '-C target-feature=+crt-static'
#
# or
#
# ```sh
# cargo build --target x86_64-unknown-linux-musl
# RUSTFLAGS='-C target-feature=+crt-static' cargo build --target x86_64-unknown-linux-gnu
# ```

# custom flags for 'rustc'
#
# `$ cargo rustc --target=x86_64-unknown-linux-musl  -- -C link-arg=-lsome_library`
#
# or write the following text to file './build.rs':
#
# ```rust
# println!("cargo:rustc-link-arg=-Clink-arg=-lsome_library");
# ```
#
# https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-arg
# https://doc.rust-lang.org/cargo/reference/config.html
# https://rust-lang.github.io/rfcs/1721-crt-static.html
rustflags = [
    # "-C", "link-arg=-lsome_library",
    # "-C", "link-arg=-Tlink-script.ld"
    # "-C", "target-feature=+crt-static"
]

[env]
# disable parallel test execution because
# unit tests contains both image creating, modification and reading.
#
# cargo test -- --test-threads=1 --show-output
#
# https://doc.rust-lang.org/book/ch11-02-running-tests.html
RUST_TEST_THREADS = "1"